### ISSUE TITLE
Options 

### ISSUE THREAD

**Issue by bjspence67** [minho42/roster-ios-public#2]
Hello , 

Thank you for the great app.

Is it possible to have it adjusted so it works well on a standard size iPhone and all that you can option to show a month or a fortnight at a time to allow for more screen space so you can see your workmates.

On a standard iPhone with larger text you cannot see or access The area where you show who’s working.

**Comment by minho42** [comment]
Hi, 
I'm aware of this issue, but I don't think I can fix it.
App store reviewing process for this app is quite strict, and it's hard for me to update anything at this stage.
But thanks for your feedback and I'll keep this in mind for potential future updates.
